### ISSUE TITLE
Help in building a module for disabling the Start Stop system

### ISSUE THREAD

**Issue by byrrt** [SHU-red/EMP2_TouchEmulator#1]
I have a 2020 Toyota Proace City Verso and I would like to disable the start stop system. I found your project and I plan to build a small STM32 board that will send change sequences via the CAN protocol. I would like to contact you to ask if you found power supply on the yellow plug after ignition or permanent power. I am also looking for information on how to check whether the ignition is on or not via the CAN bus. I am an industrial electronics designer. I live in Poland.

Best regards and I am waiting for your answer
Piotr

**Comment by SHU-red** [comment]
Sorry for the late reply
Very busy at the moment

- Same yellow 60-pin-plug at the lower right
- pin29

Should be the USB (rear compartment) supply wire turning on and off with ignition

Can you check and verify?

Thanks

**Comment by byrrt** [comment]
Hi, thank you for your reply. I will check pin 29 in the plug soon, but I will ask again - do you know how to check whether the ignition is on or not via the CAN protocol? I am afraid that the signal in the plug may be active when BSI is active, which has no direct impact on whether the ignition is on or not. Can I also connect to the CAN bus in the OBD2 socket? Are these CAN buses different buses?

I am waiting for the CANable interface to be delivered to me so that I can listen to what is happening on the bus.

**Comment by SHU-red** [comment]
I think 29 is excactly what you want.
Anyways i think the below information could be also helpful for you

&rarr; Please let me know what of the below is true, so that i can add it into my README.md

> [!Warning]
> The below information is not confirmed

Clamp 30 (Permanent 12V)

- 16pin Blue Upper middle - Pin2 --> Diagnosis Permanent 12V-Supply

Clamp 15 (12V Synchronous to ignition)

- 60pin Yellow Plug Lower Left - Pin 29 --> USB Port Back compartement
- 16pin Grey slimmer right next to the Yellow - Pin12 --> wireless Charger

**Comment by byrrt** [comment]
This weekend I will try to check the voltage on this connector because I don't have time to do it during the week.

**Comment by byrrt** [comment]
I'm sorry I haven't responded, but I had a busy weekend and I don't have time for measurements during the week. Yesterday I received the USB<>CAN adapter, so I'm motivated to get things started. I'll try to figure something out this weekend.

**Comment by byrrt** [comment]
So I had some time today and connected to the car. Unfortunately, I have the following observations:

In the yellow plug, pin 34 and 36 match the colors, but I'm not sure if it's CAN. On pin 34 - brown - when the ignition is turned on there is a voltage of about 1.5V, on pin 36 (blue) there is about 4.15V, but unfortunately when the BSI goes to sleep there is over 11V there. These wires (blue and brown) are not twisted together - they are straight.
Pin 29 may be the power supply after ignition, but in my case there is no this pin in the plug at all - it is empty. In the car I have a rear USB socket in the tunnel and an inductive charger.

Please verify whether the CAN lines have been described correctly. I took the power supply after ignition and ground from the black plug with the red release mechanism on the right side of the BSI.

![20240125_105406](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/62f28571-2f51-4710-b7c8-4568ecd72c67)
![20240125_105744](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/52781adf-0848-41ed-b89e-9a132479cfc4)
![20240125_105947](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/d8c91012-a8fd-4a60-9aa5-44b5218711cb)
![20240125_121700](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/d2ddc521-be09-4687-a01b-f5a55f125118)

**Comment by byrrt** [comment]
In the 16-pin gray plug, the 12th pin is not available and I have an inductive charger - please verify this as well. To the author of the project - where did you get the diagrams?

**Comment by SHU-red** [comment]
> In the yellow plug, pin 34 and 36 match the colors, but I'm not sure if it's CAN

If you are already planning to do a CAN-project, do you have a CAN-Sniffer and can just check if you can find communication? &rarr; If everything is matching, the chance is hight, that you will find a CAN there

Maybe considering to run the Power Supply of your board via the USB-Supply (turning ON anf OFF with vehicle ignition) like i do, so you can easily deactivate the device by just unplugging the cable out of the USB-plug?

**Comment by byrrt** [comment]
I connected an oscilloscope to pins 34 and 36 and it is a CAN bus. After the BSI module is put to sleep, the CANL line is set to almost 12V, but when the devices are working, the transmission is visible. Unfortunately, the CANable I ordered does not work - it does not see any frames coming from the bus. You can't send anything using it either. I tried to change the software to CANable/PCAN in different versions, but it doesn't change anything (on Cangaroo and PCAN-wiew software). I guess I have to buy another adapter and this is a waste of time.

Thank you very much for the documentation sent to me by e-mail - previously I also found similar documents to this BSI from the Peugeot 508 forum - the BSI is the same.

![NewFile3](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/8e637afb-4839-4ad9-ae30-6dad13655783)
![NewFile4](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/fa24389b-f8da-451e-ad54-00176b01d377)
![NewFile5](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/f3a5407c-d5f8-4f51-9d7f-7eac115795c9)

**Comment by SHU-red** [comment]
Glad to hear you are making progress!

1. I want to highlight to you again that you have to set your CAN-Module to a Baudrate of 125kBaud (125000Baud) to be able to see the messages --> Standard-Automotive is something like 500kBaud but this one is more simple
2. I want to remind you that it would be kind of you to post if you have found 12V Ignition and 12V Permanent Wires/Pins for me to add it to the description

Thanks and good luck

**Comment by byrrt** [comment]
> 1. I want to highlight to you again that you have to set your CAN-Module to a Baudrate of 125kBaud (125000Baud) to be able to see the messages --> Standard-Automotive is something like 500kBaud but this one is more simple

Yes, I set the interface to 125kHz - both in PCAN-View and Cangaroo - there was deafening silence. I ordered a second interface, in the meantime I will check this one - replace the CAN gate, etc. I am surprised that when sending something through the program, the LED on the converter does not even flash.

> 2\. I want to remind you that it would be kind of you to post if you have found 12V Ignition and 12V Permanent Wires/Pins for me to add it to the description

I connected to the wires going to the 35-pin black plug marked PAV (bottom right). I don't remember exactly which pins I connected to, but I found the ground with an ohmmeter on the car body (most probably pin 3/4) and I get 12V from one of the 8 larger pins in the plug and it was probably pin 29 - Power supply for the map reading lamp (on 508 BSI2010 documentation).

![obraz](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/b40b78ec-ae98-406c-8c11-37ce8e870373)

**Comment by byrrt** [comment]
Ok, I found the reason why the converter does not cooperate with the program. The TJA1050 chip in the converter was damaged - after replacing it, everything started working fine. I can see the CAN communication frames and am able to force the Start-Stop system to turn off. Now you need to design the board, solder it and write the program. In the meantime, I will try to run it on an STM32 evolution board.
![obraz](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/e44462c8-e177-4284-8166-a8132624793b)

**Comment by byrrt** [comment]
I know I haven't written for a long time, but the project was moving very slowly and all I did was after hours at random.
I designed, made and soldered the board:

![ss_kiler](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/571c4a9a-9b53-4eee-b7dd-1ab1787e8ec4)
![20240326_080928](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/52b379e4-099c-4d41-879f-76912f10665d)
![20240326_113325](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/25f49219-2880-4e23-9a7d-6de93d2b4b63)
![20240326_122957](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/ee92ca84-fb03-4396-b2a2-5ca2065d1a88)
![20240409_100214](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/98d1c499-c0ac-48c2-8b8b-4f114a02c31b)

Program written in C:
1) I wait 10 seconds,
2) I'm waiting for frames from BSI and NAC,
3) if S&S is turned on - I prepare a frame with NAC and send a command to change the state, if it is turned off, I wait for the system to be turned on for the first time (this will be useful, e.g. in winter, when at a temperature below 0'C the system is turned off automatically and turns on itself after the temperature warms up),
4) I wait a second and read the frame from the BSI, if the system has been turned off, I end the work, if I do not return to point 2.

For now, it's a quick program - no extras, I also configure Watchdog, and after successful transmission, I turn on the silent mode on the TJA1051 gateway (I receive, but I can't transmit).
Everything works as it should - I have been enjoying the car without this stupid system for several weeks.

**Comment by byrrt** [comment]
Yesterday I installed the module in second Toyota Proace City (Long) and I have some interesting observations.
The car is a month younger than mine, has the same equipment version, was bought in the same dealer, and there are some differences in wire colors.

Yellow EH2 connector on BSI:
pin 34 (CAN_INFO_DIV_H) - gray-brown (not brown)
pin 36 (CAN_INFO_DIV_L) - brown-white (not blue)

Additionally, I didn't see in my Toyota that the wires are twisted (as they should be) and here I could see the twisted pair.

I get power from the connector marked PAV:
![20240414_152138](https://github.com/SHU-red/EMP2_TouchEmulator/assets/25009182/f78d8b56-c97e-4838-8458-2e0ef8e10383)

I plan to extend the project even further, switch the power supply to permanent power supply (to be able to talk via CAN not only when the ignition is on) and read the ignition status/engine speed via CAN, but in my free time - the project is under development.

**Comment by SHU-red** [comment]
I am very happy for you that everything works and thank you very much for your deailled description

**Comment by sledzik1984** [comment]
For reference - I think that I've found CAN network diagram for cars like Proace City, Rifter, etc. 

At the moment Im trying to get access to CAN-INFO-DIV network to get information about headlights in my Proace - leaving the document for others. 
[ilide.info-aee2010-r3-economy-multiplexed-architecture-pr_97fbdc48bc1330fb887f25080c73d16f.pdf](https://github.com/SHU-red/EMP2_TouchEmulator/files/15377853/ilide.info-aee2010-r3-economy-multiplexed-architecture-pr_97fbdc48bc1330fb887f25080c73d16f.pdf)

[соединение сети CAN INFO DIV.pdf](https://github.com/SHU-red/EMP2_TouchEmulator/files/15378011/CAN.INFO.DIV.pdf)


I think this CAN network can be accessed easier in back compartment of the car - documetation says that there is "Parking Assist ECU" connected to that network... will check that later in my garage.

**Comment by byrrt** [comment]
> For reference - I think that I've found CAN network diagram for cars like Proace City, Rifter, etc.
> 
> At the moment Im trying to get access to CAN-INFO-DIV network to get information about headlights in my Proace - leaving the document for others. [ilide.info-aee2010-r3-economy-multiplexed-architecture-pr_97fbdc48bc1330fb887f25080c73d16f.pdf](https://github.com/SHU-red/EMP2_TouchEmulator/files/15377853/ilide.info-aee2010-r3-economy-multiplexed-architecture-pr_97fbdc48bc1330fb887f25080c73d16f.pdf)
> 
> [соединение сети CAN INFO DIV.pdf](https://github.com/SHU-red/EMP2_TouchEmulator/files/15378011/CAN.INFO.DIV.pdf)
> 
> I think this CAN network can be accessed easier in back compartment of the car - documetation says that there is "Parking Assist ECU" connected to that network... will check that later in my garage.

Hi, it looks very promising.  While looking at it with a can sniffer, I saw frames with the status of the lights.  I wanted to add a lot more to the module I created, but over time it is even worse than before.  You seem to be from poland (like me) - would you write to me?  byrrt dot pb monkey gmail dot com.
